name: Deploy to Azure App Service

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Azure CLI
      uses: azure/cli@v1
      with:
        azcliversion: latest

    - name: Login to Azure
      run: az login --service-principal -u ${{ secrets.AZUREAPPSERVICE_CLIENTID }} -p ${{ secrets.AZUREAPPSERVICE_CLIENTSECRET }} --tenant ${{ secrets.AZUREAPPSERVICE_TENANTID }}

    - name: Set subscription
      run: az account set --subscription ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID }}

    - name: Deploy to Azure Web App
      run: |
        az webapp deployment source config --name <your-web-app-name> --resource-group <your-resource-group> --branch main --repo <repository-url> --manual-integration

